### PR TITLE
add some strategems

### PR DESCRIPTION
**Pull request by qq99**
Nicely rendered view: https://github.com/Shopify/turbograft/blob/tg-docs/docs/strategems.md

### CODE REVIEW

**Comment by qq99** [comment]
cc @Shopify/tnt thoughts? comments? criticisms?

At some point I thought this might be useful, but now I'm less satisfied with it now that I've written it.  But I've gone past the point of no return so here's a PR!

Any things I should add?  I know it's missing `Perform an action and partially refresh` and an example of refreshing multiple nodes using a single refresh key or refreshing multiple nodes using multiple refresh keys, but, I'm not sure that's necessary?

**Comment by celsodantas** [comment]
I like the idea. But maybe we should keep it in the wiki?

**Comment by qq99** [comment]
Great point lol

**Comment by qq99** [comment]
https://github.com/Shopify/turbograft/wiki/TurboGraft-Strategems

**Pull request closed without merging**
