### PR TITLE
make turbolinks run scripts of child nodes on replace

### PR DESCRIPTION
**Pull request by kristianpd**
WIP

This makes sure any scripts nested in a node being replaced are run unless they're not supposed to.

### CODE REVIEW

**Comment by pushrax** [comment]
Rebasing off master will fix the build.

**Comment by akrav** [comment]
@kristianpd Can you get this change into master?

**Comment by qq99** [comment]
Looks legit :+1:

**Comment by akrav** [comment]
cc @Shopify/tnt
@pushrax Can you get this change into master?

**Comment by patrickdonovan** [comment]
The test failures are legit - just guessing but it's probably because in the case when the root node of the swapped-in html is a script tag, it gets missed by `node.querySelectorAll 'script:not([data-turbolinks-eval="false"])'` Haven't had time to fix it.

**Pull request closed without merging**
